# Generated by Django 4.1.4 on 2023-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.EmailField(max_length=100)),
                ('address2', models.EmailField(max_length=100)),
                ('city', models.EmailField(max_length=100)),
                ('state', models.EmailField(max_length=100)),
                ('pin', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
